language: python
os: linux

git:
  depth: 1

osx_image: xcode10

dist: bionic

jobs:
  include:
    # Linux
    - env: TARGET=x86_64-unknown-linux-gnu
      os: linux

    # # OSX
    # - env: TARGET=x86_64-apple-darwin
    #   os: osx
    #
    # # Windows
    # - env: TARGET=x86_64-pc-windows-gnu
    #   os: windows

before_script:
  # Install required Python versions
  - sudo add-apt-repository ppa:deadsnakes/ppa -y
  - sudo apt install python3.{6..8} python3.{6..8}-dev -y;

  # Clone Austin development branch
  - git clone --branch devel --depth 1 https://github.com/P403n1x87/austin.git ../austin

  # Compile Austin
  - cd ../austin;
    if [[ "$TRAVIS_OS_NAME" == "linux" ]];
    then
      gcc -Wall -O3 -Os -s -pthread src/*.c -o src/austin;
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]];
    then
      gcc -Wall -O3 -Os -o src/austin.exe src/*.c -lpsapi;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]];
    then
      gcc -Wall -O3 -Os src/*.c -o src/austin;
    fi;
    cd -

  # Install Austin
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]];
  #   then
  #     sudo snap install austin --classic;
  #   elif [[ "$TRAVIS_OS_NAME" == "windows" ]];
  #   then
  #     choco install austin;
  #   elif [[ "$TRAVIS_OS_NAME" == "osx" ]];
  #   then
  #     brew install austin;
  #   fi;

  - pip install nox==2020.5.24
  - pip install poetry==1.0.5

script: |
  export PATH="../austin/src:$PATH";
  if [[ "$TRAVIS_OS_NAME" == "linux" ]];
  then
    nox;
  elif [[ "$TRAVIS_OS_NAME" == "windows" ]];
  then
    nox;
  elif [[ "$TRAVIS_OS_NAME" == "osx" ]];
  then
    sudo nox;
  fi;
